name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
jobs:
  YoooThisIsMyNewJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hey GH, ${{ github }}"
      - run: echo "hey runner, ${{ runner }}"
      - name: This is name
        run: echo "eeeeeeeeeee1!"
      - name: Show pwd www
        run: |
          pwd
      - name: Show pwd of ws
        run: echo ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
  twoJobs:
  twoTimes(Clap):
