name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
jobs:
  deploy-my-pages:
    runs-on: ubuntu-latest
    steps:
      # - name: Configure GitHub Pages
      #   uses: actions/configure-pages@v4.0.0
      # - name: Upload GitHub Pages artifact
      #   uses: actions/upload-pages-artifact@v2.0.0
      # - name: Deploy GitHub Pages site
      #   uses: actions/deploy-pages@v3.0.1
      - run: echo Hello, $HEY
        env:
          HEY: Abiria
      - run: echo Halo, $HEY
        env:
          HEY: kokok
      - run: echo こんにちは, $HEY
        env:
          HEY: kokok
