name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
env:
  HEY: Abiria
jobs:
  deploy-my-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4.0.0
        with:
          enablement: true
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3.0.1
