name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
jobs:
  deploy-my-pages:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4.0.0
        with:
          enablement: true
          token: ${{ secrets.CONFIGURE_PAGES_PAT }}
      - run: echo '<h1>Hellllo GHA!!<h1>' > index.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: .
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3.0.1
        id: deployment
  env2:
    environment:
      name: yeeeeeeenvironment!!
      url: https://google.com
      steps:
        run: echo A
