name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
jobs:
  a1:
    runs-on: ubuntu-latest
    steps:
      run: echo "yo"
  b1:
    needs: a1
    runs-on: ubuntu-latest
    steps:
      run: echo "yo"
  b2:
    needs: a1
    runs-on: ubuntu-latest
    steps:
      run: echo "yo"
  c1:
    needs: [b1, b2]
    runs-on: ubuntu-latest
    steps:
      run: echo "yo"
