name: GitHub Action DemoEEEEE
run-name: '${{ github.actor }} is testing out GitHub Actions :rocket:'
on:
  - push
jobs:
  a1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  b1:
    needs: a1
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  b2:
    needs: a1
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  c1:
    needs: [b1, b2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  c2:
    needs: [b1, b2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  c3:
    needs: [b1, b2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  d1:
    needs: [c1, c2, c3]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  d2:
    needs: [c1, c2, c3]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
  e1:
    needs: [d1, d2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "yo"
